Repository uc-cdis/cdis-jenkins-lib, pull requests merged in 2020-10, with the labels that each got.

#121 fix(ci): Fix for sower block service account substitution
  vars/manifestHelper.groovy
Labels: test-apis-metadataIngestionTest

#122 fix(ci): Sower block null check
  vars/manifestHelper.groovy
Labels: test-portal-homepageTest

#124 chore(qa): Skip WaitForQuayBuild stage for cdis-jenkins-lib PRs
  vars/quayHelper.groovy
Labels: test-portal-homepageTest

#127 add CODEOWNERS file to doc_only
  vars/docOnlyHelper.groovy
Labels: test-portal-indexingPageTest

#128 fix(ci): Mutate indexs3client blocks in jenkins environments manifests
  vars/manifestHelper.groovy
Labels: test-portal-dataUploadTest

#129 chore(ci2): Also delete svc acct keys for ci-env-1
  vars/microservicePipelineK8s.groovy
  vars/testHelper.groovy
Labels: test-portal-homepageTest
