Repository uc-cdis/cdis-jenkins-lib, pull requests merged in 2021-05, with the labels that each got.

#174 chore(k8s-jenkins-ci): Update k8s microservices pipeline script
  vars/microservicePipelineK8s.groovy
Labels: test-portal-homepageTest

#173 chore(ci-observability): Send slack notifications for K8sReset failures
  vars/kubeHelper.groovy
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#175 chore(ci-observability): hudson.AbortException should not be considered a k8sReset failure
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#171 Chore(ci): Modify label mechanism by only parsing result*.xml
  vars/testHelper.groovy
  vars/xmlHelper.groovy
Labels: test-portal-dataUploadTest, test-portal-homepageTest

#176 Handle swagger doc at any path
  vars/docOnlyHelper.groovy
Labels: test-portal-homepageTest

#177 Fix: delete netpolicy in jenkins when target environment manifest does not have it
  vars/manifestHelper.groovy
Labels: test-portal-homepageTest

#159 chore(ci): Parallel testing (1st iteration).
  vars/ciEnvsHelper.groovy
  vars/microservicePipeline.groovy
  vars/pipelineHelper.groovy
  vars/testHelper.groovy
Labels: jenkins-niaid, parallel-testing, test-apis-drsEndpointsTest, test-apis-metadataIngestionTest, test-pidgin-getCoremetadataTest, test-portal-homepageTest

#178 chore(ci): Create bridge function to support typo for old cloud-automation PRs
  vars/ciEnsPoolHelper.groovy
Labels: test-portal-homepageTest

#180 fix(ci): doc-only flow should not rely on testedEnv
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#181 chore(nightly-build): Include nightly-run label when sending replay msgs
  vars/testHelper.groovy
Labels: nightly-run, test-portal-homepageTest

#182 fix(ci): fix jq instruction to print sower_block.json
  vars/manifestHelper.groovy
Labels: test-portal-homepageTest

#184 fix(nightly-build): testedEnv should be determined by global config, not by git diff folder
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#185 fix(logging): print testedEnv
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#186 fix : double quotes to check the length func sower block
  vars/manifestHelper.groovy
Labels: test-portal-homepageTest

#187 fix(ci): Setting testedEnv properly for service, manifest and nightly-builds CI runs
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest
