Repository uc-cdis/cdis-jenkins-lib, pull requests merged in 2021-07, with the labels that each got.

#196 chore(ci): Introduce special label to run PR check on separate jenkins-ci-worker pod
  vars/ciEnvsHelper.groovy
  vars/microservicePipeline.groovy
Labels: test-apis-cleverSafeTest, test-apis-dataUploadTest, test-apis-exportToWorkspaceTest, test-apis-metadataIngestionTest, test-portal-dataUploadTest, test-portal-indexingPageTest

#200 display namespace after try block
  vars/microservicePipeline.groovy
Labels: run-on-jenkins-ci-worker

#202 chore(ci-mgmt): Delete 3rdParty resources from new jenkins env
  vars/testHelper.groovy
Labels: test-google-googleServiceAccountRemovalTest

#194 chore(nightly-build): Improve nightly-build test coverage with long-running tests
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#203 fix(nightly-build): Fix nightly build test addition
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest

#205 chore(nightly-build): Identify which environment is being tested as part of the nightly build.
  vars/manifestHelper.groovy
  vars/microservicePipeline.groovy
Labels: test-portal-homepageTest
